Sample.targets

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/2)

Fix Signing

---

BaseInstallerBuild/TemplateFramework.wxs
Common/CustomFeatures.wxi

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/6)

Custom Folders and Features

---

BaseInstallerBuild/Bundle.wxs
BaseInstallerBuild/Framework.wxs
BaseInstallerBuild/OfflineBundle.wxs
BaseInstallerBuild/buildBaseInstaller.bat
Common/Redistributables.wxi
CreateUpdatePatch/buildPatch.bat

* Add 64bit redistributables
* Allow redistributable selection to be customized
* Use a 64bit component when building for x64
* Create separate base dirs per platform
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/15)

Support 64bit installation

---

BaseInstallerBuild/Framework.wxs

Resolves [7](https://github.com/sillsdev/genericinstaller/issues/7)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/17)

7: Uninstall Settings Directory Registry Key

---

BaseInstallerBuild/Framework.wxs
Common/CustomComponents.wxi
Common/CustomFeatures.wxi
Common/Overrides.wxi

* Move all features except MainApplication to CustomFeatures.wxi
* Include sample data in overridable files (Common)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/16)

Template Overridable Files

---

BaseInstallerBuild/BundleTheme.xml

* Modified the Page Install Text content height increased.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/19)

Fix : LT-18744 [GI] License Terms is hidden by other text

---

BaseInstallerBuild/Framework.wxs
BaseInstallerBuild/buildBaseInstaller.bat
Common/Overrides.wxi
CreateUpdatePatch/AppNoUi.wxs
CreateUpdatePatch/buildPatch.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/18)

Good Enough For Now: Two Data Dirs

---

BaseInstallerBuild/BundleTheme.xml

* Modified the height and did some tricks in the image height
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/20)

Fix: LT-18745 [GI] Alt key hides Welcome and accept license

---

BaseInstallerBuild/BundleTheme.wxl
BaseInstallerBuild/BundleTheme.xml

* Modified the design slightly and Checkbox Text Accept Alt+A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/21)

Fix: LT-18745 [GI] Alt-A should accept license

---

BaseInstallerBuild/Framework.wxs

* Included the project registry to get the setting value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/27)

Fix: LT-19083 When "Repair" resets ProjectsDir to C:\

---

BaseInstallerBuild/buildBaseInstaller.bat
CreateUpdatePatch/buildPatch.bat

ICE validation must be run with administrator privileges.
The jenkins user is not an administrator.
Therefore, suppress ICE validation so it doesn't fail.
Add WIX to the PATH in the patch batch script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/29)

Suppress ICE Validation

---

BaseInstallerBuild/Framework.wxs
BaseInstallerBuild/buildBaseInstaller.bat
CreateUpdatePatch/AppNoUi.wxs
CreateUpdatePatch/buildPatch.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/31)

Make Patching Work

---

BaseInstallerBuild/Bundle.wxs
Common/Patch.wxi

* Included to add the patch msp in build process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/32)

Fix: LT-19171 Installer should automatically install the patch

---

BaseInstallerBuild/Framework.wxs

* Included the creating a folder for the DataFolder
* Added the security credentials
* When uninstall this folder won't remove by installer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/34)

Fix: LT-19167 Database folder not installed

---

CreateUpdatePatch/AppNoUi.wxs
CreateUpdatePatch/buildPatch.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/37)

FLEx Bridge patching cherry-picks

---

BaseInstallerBuild/Framework.wxs
BaseInstallerBuild/buildBaseInstaller.bat
CreateUpdatePatch/buildPatch.bat

A firewall exception is required by LT-19007
Change-Id: I7fae39d495c340d6efe22128a93d5331dcdba0fb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/38)

Allow clients to use the WiX Firewall Extension

---

BaseInstallerBuild/Framework.wxs
BaseInstallerBuild/buildBaseInstaller.bat
Common/Overrides.wxi

* Addresses Fieldworks bug LT-19399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/42)

Fix installer to work regardless of UI Language

---

BaseInstallerBuild/Bundle.wxs
Common/Patch.wxi

Instead of this strategy, we plan to find and install patches when the
application runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/36)

Revert "Fix: LT-19171 Installer should automatically install the patch"

---

BaseInstallerBuild/Bundle.wxs
BaseInstallerBuild/OfflineBundle.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/52)

Depend on .NET 4.8

---

BaseInstallerBuild/Framework.wxs
BaseInstallerBuild/WixUI_en-us.wxl

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/54)

Use Previous Install Location, if any

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/57)

Escape angle brackets in README.md

---

BaseInstallerBuild/Bundle.wxs

Solves security problems
Prevents clutter being left in the root directory.
Resolves https://jira.sil.org/browse/LT-20315 and LT-20554
Change-Id: Ic1f9e638645b8efe44eb744c345a3aa5534915e1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/58)

Update Visual C++ 2008 Redistributable

---

BaseInstallerBuild/Bundle.wxs
BaseInstallerBuild/OfflineBundle.wxs

* Update the Visual C++ 2010 Redistributable
* Rename the Visual C++ 2010 Redistributable to match others
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/59)

[API] Apply MFC Security Update to vcredist 2010

---

BaseInstallerBuild/Bundle.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/61)

Fix error with vc15to19 redistributables

---

CreateUpdatePatch/AppNoUi.wxs

Change-Id: Icd3f5bccc98b769488e5a6e8e6b5a788f84cedcc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/67)

Fix path to ProcRunner

---

BaseInstallerBuild/Framework.wxs
Common/CustomActionSteps.wxi
Common/Overrides.wxi

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/69)

Add an extension point for client provided custom actions

---

BaseInstallerBuild/signingProxy.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/76)

Collect filenames to be signed instead of just skipping

---

BaseInstallerBuild/buildExe.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/77)

Add parameter to buildExe.bat to facilitate remote signing

---

BaseInstallerBuild/buildExe.bat
BaseInstallerBuild/signingProxy.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/genericinstaller/78)

Fix several signtool related regressions
